apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
  namespace: demo
type: Opaque
stringData:
  DB_PASSWORD: "YourStrong!Passw0rd"
  JWT_SIGNING_KEY: "dev-jwt-signing-key-change-me"
  APP_ENCRYPTION_KEY: "dev-app-encryption-key-change-me"
