apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubecart-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: kubecart.local
      http:
        paths:
          # UI
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ui-service
                port:
                  number: 80

          # Identity
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: identity-service
                port:
                  number: 80

          # Catalog
          - path: /api/catalog(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalog-service
                port:
                  number: 80

          # Orders
          - path: /api/orders(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: orders-service
                port:
                  number: 80
