apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: demo
data:
  DB_HOST: 172.27.16.1,1433
  DB_NAME: KubeCart_Orders
  DB_USER: sa
  CATALOG_SERVICE_URL: http://catalog-service.demo.svc.cluster.local
