apiVersion: v1
kind: Secret
metadata:
  name: kubecart-jwt
  namespace: demo
type: Opaque
stringData:
  Jwt__SigningKey: "REPLACE_ME"
  Jwt__Issuer: "KubeCart.Identity"
  Jwt__Audience: "KubeCart.Client"
  Jwt__ExpiresMinutes: "60"
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecart-internal-api-key
  namespace: demo
type: Opaque
stringData:
  INTERNAL_API_KEY: "REPLACE_ME"
